{"name": "Проверяем изменение имени без авторизации", "status": "passed", "description": "Создаём пользователя и меняем имя, отправляя пустой accessToken. Проверяем, что вернулась ошибка. Текст ошибки: \"You should be authorised\". После проверки удаляем юзера", "steps": [{"name": "Создаём юзера", "status": "passed", "start": 1717572717177, "stop": 1717572717444}, {"name": "Изменяем данные юзера", "status": "passed", "start": 1717572717444, "stop": 1717572717649}, {"name": "Удаляем юзера", "status": "passed", "start": 1717572717649, "stop": 1717572718123}], "start": 1717572717177, "stop": 1717572718123, "uuid": "b591efb5-9748-4743-8c06-056003d5858e", "historyId": "24fa250dc0a9b80bb449f8c0dd04cf2c", "testCaseId": "24fa250dc0a9b80bb449f8c0dd04cf2c", "fullName": "tests.test_changing_user_data.TestChangingUserData#test_change_name_without_authorization", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_changing_user_data"}, {"name": "subSuite", "value": "TestChangingUserData"}, {"name": "host", "value": "Kotiki"}, {"name": "thread", "value": "15004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_changing_user_data"}]}